import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import solc from "solc";
const require = createRequire(import.meta.url);
export const root = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
export function compile() {
  const sources = Object.fromEntries(
    [
      "CredibleExecBond.sol",
      "test/TestToken.sol",
      "test/TestExecution.sol",
      "test/ReentrantToken.sol",
    ].map((name) => [
      name,
      {
        content: fs.readFileSync(
          path.join(root, "contracts/src", name),
          "utf8",
        ),
      },
    ]),
  );
  const output = JSON.parse(
    solc.compile(
      JSON.stringify({
        language: "Solidity",
        sources,
        settings: {
          optimizer: { enabled: true, runs: 200 },
          evmVersion: "shanghai",
          outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
        },
      }),
      {
        import: (name: string) => {
          try {
            return { contents: fs.readFileSync(require.resolve(name), "utf8") };
          } catch {
            return { error: `Missing import: ${name}` };
          }
        },
      },
    ),
  );
  const errors = output.errors?.filter(
    (e: { severity: string }) => e.severity === "error",
  );
  if (errors?.length) throw new Error(JSON.stringify(errors));
  const artifacts: Record<
    string,
    { abi: import("viem").Abi; bytecode: `0x${string}` }
  > = {};
  for (const contracts of Object.values(output.contracts) as Record<
    string,
    { abi: import("viem").Abi; evm: { bytecode: { object: string } } }
  >[]) {
    for (const [name, c] of Object.entries(contracts))
      if (c.evm.bytecode.object)
        artifacts[name] = {
          abi: c.abi,
          bytecode: `0x${c.evm.bytecode.object}`,
        };
  }
  return artifacts;
}
if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const artifacts = compile();
  fs.mkdirSync(path.join(root, "contracts/artifacts"), { recursive: true });
  for (const [name, artifact] of Object.entries(artifacts))
    fs.writeFileSync(
      path.join(root, "contracts/artifacts", `${name}.json`),
      JSON.stringify(artifact, null, 2),
    );
  fs.mkdirSync(path.join(root, "packages/domain/src"), { recursive: true });
  fs.writeFileSync(
    path.join(root, "packages/domain/src/bond-abi.ts"),
    `// Generated by pnpm contracts:build.\nexport const bondAbi = ${JSON.stringify(artifacts.CredibleExecBond.abi, null, 2)} as const;\n`,
  );
  console.log("Compiled bond and test token; generated shared ABI.");
}
